# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/libkdepim' : '@same'
    'pim/mailimporter' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'

Options:
  cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]      
