# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kdesignerplugin' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/akonadi-mime' : '@latest'
    'kde/pim/kmailtransport' : '@latest'
    'kde/pim/kmime' : '@latest'
    'kde/pim/libkdepim' : '@latest'
    'kde/pim/mailimporter' : '@latest'
    'kde/pim/messagelib' : '@latest'
    'kde/pim/pimcommon' : '@latest'
